version: "3.1"
services:
 users:
  build: ./users
  restart: always 
  image: users:latest
  links:
  - db
  ports:
  - "8080:80"
 rides:
  build: ./rides
  restart: always
  image: rides:latest
  links:
  - db1
  ports:
   - "8000:80"

 db:
  image: mysql:5.7
  ports:
  - "32000:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=users
  volumes:
  - ./db:/docker-entrypoint-initdb.d/:ro
 db1:
  image: mysql:5.7
  ports:
  - "32001:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=rides
  volumes:
  - ./db:/docker-entrypoint-initdb.d/:ro
